# docker-compose.yml
version: '3'
services:
  database:
    # Image used by Railway app
    image: "postgres:11.21-alpine3.18" 
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"  
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
  preview-example:
    build: ./src
    ports:
      - "8080:8080"
    depends_on:
      - database      
volumes:
  database-data: # named volumes can be managed easier using docker-compose